@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

package ru.yandex.practicum.smarthome.service {
    interface HeatingSystemService {
        +HeatingSystemDto getHeatingSystem(Long id)
        +HeatingSystemDto updateHeatingSystem(Long id, HeatingSystemDto heatingSystemDto)
        +void turnOn(Long id)
        +void turnOff(Long id)
        +void setTargetTemperature(Long id, double temperature)
        +Double getCurrentTemperature(Long id)
    }
}

package ru.yandex.practicum.smarthome.dto {
    class HeatingSystemDto {
        +Long id
        +String name
        +double targetTemperature
        +double currentTemperature
        +boolean isOn
    }
}

package ru.yandex.practicum.smarthome.entity {
    class HeatingSystem {
        +Long id
        +String name
        +double targetTemperature
        +double currentTemperature
        +boolean isOn
    }
}

package ru.yandex.practicum.smarthome.controller {
    class HeatingController {
        -HeatingSystemService heatingSystemService
        -HeatingStorageManager heatingStorageManager
        +HeatingController(HeatingSystemService heatingSystemService, HeatingStorageManager heatingStorageManager)
        +HeatingSystemDto getHeatingSystem(Long id)
        +HeatingSystemDto updateHeatingSystem(Long id, HeatingSystemDto heatingSystemDto)
        +void turnOn(Long id)
        +void turnOff(Long id)
        +void setTargetTemperature(Long id, double temperature)
        +Double getCurrentTemperature(Long id)
    }
}

package ru.yandex.practicum.smarthome.storage {
    class HeatingStorageManager {
        -HeatingSystemRepository heatingSystemRepository
        +HeatingStorageManager(HeatingSystemRepository heatingSystemRepository)
        +HeatingSystem save(HeatingSystem heatingSystem)
        +HeatingSystem findById(Long id)
        +void deleteById(Long id)
    }
}

package ru.yandex.practicum.smarthome.repository {
    interface HeatingSystemRepository {
        +HeatingSystem save(HeatingSystem heatingSystem)
        +HeatingSystem findById(Long id)
        +void deleteById(Long id)
    }
}

HeatingController --> HeatingSystemService : uses
HeatingController --> HeatingStorageManager : uses
HeatingStorageManager --> HeatingSystemRepository : uses
HeatingSystemService --> HeatingSystemDto : returns
HeatingSystemService --> HeatingSystem : uses

@enduml