@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь Smart Home System")
System_Boundary(system, "Система Умный дом") {
    Container(apiGateway, "АPI Gateway", "Kusk", "Маршрутизация запросов, мониторинг, логирование, аутентификация и авторизация")

    Container(heating_control, "Heating Control Service", "Java and Spring MVC", "Управляет отоплением") {
        Component(heating_controller, "Heating Controller", "Управление отоплением")
        Component(heating_command_producer, "Heating Command Producer", "Отправка команд")
        Component(heating_storage_manager, "Heating Data Storage Manager", "Сохранение данных")
        Rel(heating_controller, heating_command_producer, "")
        Rel(heating_controller, heating_storage_manager, "")
    }

    Container(sensor_management, "Sensor Management Service (Telemetry)", "Java and Spring MVC", "Управляет датчиками температуры") {
        Component(sensor_controller, "Sensor Controller", "Управление датчиками")
        Component(sensor_storage_manager, "Sensor Data Storage Manager", "Сохранение данных")
        Component(sensor_data_consumer, "Sensor Data Consumer", "Сбор данных с датчиков [kafka]")
        Rel(sensor_controller, sensor_storage_manager, "")
        Rel(sensor_data_consumer, sensor_storage_manager, "")
    }

    Container(user_management, "User Service", "Java and Spring MVC", "Управление пользователями") {
        Component(user_controller, "User Management Controller", "Обработка запросов на управление пользователями")
        Component(user_storage_manager, "User Data Storage Manager", "Сохранение данных")
        Rel(user_controller, user_storage_manager, "")
    }

    ContainerDb(heating_control_db, "Database", "PostgreSQL")
    ContainerDb(sensor_management_db, "Database", "PostgreSQL")
    ContainerDb(user_db, "Database", "PostgreSQL")
    ContainerQueue(kafka, "Databus", "Kafka")

    Rel(apiGateway, heating_control, "Отправляет команды для управления отоплением", "REST API, JSON/HTPPS")
    Rel(apiGateway, sensor_management, "Запрашивает данные о температуре в помещении: последняя, за период", "REST API, JSON/HTPPS")
    Rel(apiGateway, user_management, "Запрашивает/обновляет данные о пользователе", "REST API, JSON/HTPPS")

    Rel(heating_command_producer, kafka, "Отправляет команды")
    Rel_L(kafka, sensor_data_consumer, "Отправляет данные")

    Rel(heating_storage_manager, heating_control_db, "Чтение / запись [SQL]")
    Rel(sensor_storage_manager, sensor_management_db, "Чтение / запись [SQL]")
    Rel(user_storage_manager, user_db, "Чтение / запись [SQL]")
}

System_Ext(heating_system, "Heating system", "Система отопления")
System_Ext(temperature_sensor, "Temperature sensor", "Датчик температуры")

Rel(kafka, heating_system, "Отправляет команды для управления отоплением", "REST API, JSON/HTPPS")
Rel(temperature_sensor, kafka, "Запрашивает данные о температуре в помещении", "REST API, JSON/HTPPS")
Rel(user, apiGateway, "Использует для управления отоплением")

@enduml